### ISSUE TITLE
update script to include more current version of easy-creds

### ISSUE THREAD

**Issue by 0E800** [ZEROF/BackBox-Scripts#1]
I understand this this script is over 2 years old. Just wanted to point out that there is a slightly more updated version of easy-creds (3.8-dev); the wget link should be updated.

**Comment by ZEROF** [comment]
Hi,

I will check and updated easy-creds install script.

EDIT: I get error: "Couldn't find mdk3". To fix that you will need to check my forum post: https://forum.backbox.org/howtos/install-3-in-backbox-4-%28patch-included%29/

EDIT 1: mdk3 installation now is integrated in my script, no need for manual installation from instruction provided on forum.

EDIT 3: Fixed some small bugs, and some part of installation will not work, i will try to fix them because easy-creds installation script fails to make some directories etc., not on my side, but i think that i can add fix to my script without playing with other settings.

EDIT 4: Working on fixing last issues. Problem is coming from easy-creds install.sh script and i will contact dev to fix them, or people can use my solution without problem. Work in progress .. Will update in next 2 days or less.

Thanks for information.
